name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: 24.2.6
          extra_plugins: |
            @semantic-release/commit-analyzer@13
            @semantic-release/release-notes-generator@14
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/github@11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
